name: Renovate

on:
  # configure manual trigger
  workflow_dispatch:

env:
  # The Dagger CLI uses the DAGGER_CLOUD_TOKEN environment variable to authenticate with Dagger Cloud
  DAGGER_CLOUD_TOKEN: ${{ secrets.DAGGER_CLOUD_TOKEN }}

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Install Dagger CLI
        run: cd /usr/local && { curl -L https://dl.dagger.io/dagger/install.sh | sh; cd -; }
      - name: Environment infos
        run: env | sort
      - name: Display Helm module functions
        run: dagger functions
      - name: Dagger renovate
        env:
          MY_GH_PAT: ${{ secrets.MY_GH_PAT }}
          MY_GH_WRITE_PAT: ${{ secrets.MY_GH_WRITE_PAT }}
        run: |
          dagger call gh \
              --config ./config/config.json5 \
              --github-read-token env:MY_GH_PAT \
              --github-write-token env:MY_GH_WRITE_PAT \
              --renovate-repositories "['chrira/dagger-module-helm-genius']" \
              --docker-sock /var/run/docker.sock
